name: Auto-merge Dependabot PRs

on:
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success'
    steps:
      - name: Merge Dependabot PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Loop through every PR attached to this successful check suite
            for (const pr of context.payload.check_suite.pull_requests) {
              // Only merge PRs opened by Dependabot
              if (pr.user.login !== 'dependabot[bot]') continue;

              // Merge using squash (change to 'merge' or 'rebase' if you prefer)
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            }
