name: Sync dev with main

on:
  schedule:
    - cron: '0 0 * * *' # This runs every day at midnight, adjust as needed
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to use the latest version

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge main into dev
        run: git merge origin/main || echo "Merge conflict detected, aborting." && git merge --abort

      - name: Push changes
        run: |
          if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
            git push origin dev
          else
            echo "No changes to push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
